states_of_us_alphabeta = ["Alabama",
"Alaska",
"Arizona",
"Arkansas",
"California",
"Colorado",
"Connecticut",
"Delaware",
"Florida",
"Georgia",
"Hawaii",
"Idaho",
"Illinois",
"Indiana",
"Iowa",
"Kansas",
"Kentucky",
"Louisiana",
"Maine",
"Maryland",
"Massachusetts",
"Michigan",
"Minnesota",
"Mississippi",
"Missouri",
"Montana",
"Nebraska",
"Nevada",
"New Hampshire",
"New Jersey",
"New Mexico",
"New York",
"North Carolina",
"North Dakota",
"Ohio",
"Oklahoma",
"Oregon",
"Pennsylvania",
"Rhode Island",
"South Carolina",
"South Dakota",
"Tennessee",
"Texas",
"Utah",
"Vermont",
"Virginia",
"Washington",
"West Virginia",
"Wisconsin",
"Wyoming"
]

states_of_us_by_date = ["Delaware",
"Pennsylvania",
"New Jersey",
"Georgia",
"Connecticut",
"Massachusetts",
"Maryland",
"South Carolina",
"New Hampshire",
"Virginia",
"New York",
"North Carolina",
"Rhode Island",
"Vermont",
"Kentucky",
"Tennessee",
"Ohio",
"Louisiana",
"Indiana",
"Mississippi",
"Illinois",
"Alabama",
"Maine",
"Missouri",
"Arkansas",
"Michigan",
"Florida",
"Texas",
"Iowa",
"Wisconsin",
"California",
"Minnesota",
"Oregon",
"Kansas",
"West Virginia",
"Nevada",
"Nebraska",
"Colorado",
"North Dakota",
"South Dakota",
"Montana",
"Washington",
"Idaho",
"Wyoming",
"Utah",
"Oklahoma",
"New Mexico",
"Arizona",
"Alaska",
"Hawaii"
]

print(states_of_us_by_date[42])

third_state_in_union = states_of_us_by_date[2]

print(third_state_in_union)

states_of_us_by_date.append("Ryanka")
new_state_of_ryan = states_of_us_by_date[50]
print(new_state_of_ryan)
print(states_of_us_by_date)

states_of_us_by_date.extend(["Chapelhoma", "Seven of Nineaii"])

print(states_of_us_by_date[51])
print(states_of_us_by_date)